import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import shopsRouter from "./shops.js";
import ordersRouter from "./orders.js";
import checkoutRouter from "./checkout.js";
import adminRouter from "./admin.js";
import uploadRouter from "./upload.js";
import subscriptionRouter from "./subscription.js";
import messagesRouter from "./messages.js";
import shopRouter from "./shop.js";
import escrowRouter from "./escrow.js";
import inventoryRouter from "./inventory.js";
import shipmentsRouter from "./shipments.js";
import analyticsRouter from "./analytics.js";
import affiliatesRouter from "./affiliates.js";
import aiRouter from "./ai.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/shops", shopsRouter);
router.use("/orders", ordersRouter);
router.use("/checkout", checkoutRouter);
router.use("/admin", adminRouter);
router.use("/upload", uploadRouter);
router.use("/subscription", subscriptionRouter);
router.use("/messages", messagesRouter);
router.use("/shop", shopRouter);
router.use("/escrow", escrowRouter);
router.use("/inventory", inventoryRouter);
router.use("/shipments", shipmentsRouter);
router.use("/analytics", analyticsRouter);
router.use("/affiliates", affiliatesRouter);
router.use("/ai", aiRouter);

export default router;
