kind = "mobile"
previewPath = "/mobile/"
title = "Coastaq Mobile App"
version = "1.0.0"
id = "artifacts/coastaq-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 19385

[services.development]
run = "pnpm --filter @workspace/coastaq-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/coastaq-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/coastaq-mobile", "run", "serve" ]

[services.env]
PORT = "19385"
BASE_PATH = "/mobile/"
