type FindCat = (name: string) => string | null;

export interface ProductSeed {
  title: string;
  description: string;
  price: string;
  stock: number;
  condition: "NEW" | "USED" | "REFURBISHED";
  location: string;
  images: string[];
  categoryId: string | null;
  shopId: string;
}

// Verified working Unsplash photo IDs
const P = {
  iphone:       "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop",
  macbook:      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop",
  headphones:   "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
  samsung:      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=600&fit=crop",
  generator:    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  sofa:         "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop",
  car:          "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600&h=600&fit=crop",
  shoes:        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
  electronics:  "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=600&fit=crop",
  camera:       "https://images.unsplash.com/photo-1502920917128-1aa4a5be7fc5?w=600&h=600&fit=crop",
  gaming:       "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop",
  tv:           "https://images.unsplash.com/photo-1593359677880-a63ec764ec62?w=600&h=600&fit=crop",
  laptop:       "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop",
  tablet:       "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=600&h=600&fit=crop",
  keyboard:     "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop",
  router:       "https://images.unsplash.com/photo-1544197150-b99a580bb5d3?w=600&h=600&fit=crop",
  printer:      "https://images.unsplash.com/photo-1612198188060-c7c2a3b75bc8?w=600&h=600&fit=crop",
  monitor:      "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=600&h=600&fit=crop",
  ps5:          "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&h=600&fit=crop",
  bus:          "https://images.unsplash.com/photo-1449965408869-eef56a82b5a7?w=600&h=600&fit=crop",
  excavator:    "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
  motorcycle:   "https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=600&h=600&fit=crop",
  truck:        "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=600&fit=crop",
  boat:         "https://images.unsplash.com/photo-1505236732171-6e5d8e5cc807?w=600&h=600&fit=crop",
  carparts:     "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop",
  rental:       "https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=600&h=600&fit=crop",
  apartment:    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=600&fit=crop",
  house:        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&h=600&fit=crop",
  land:         "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=600&fit=crop",
  office:       "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=600&fit=crop",
  building:     "https://images.unsplash.com/photo-1486406154986-e4ce3a2d39e0?w=600&h=600&fit=crop",
  shortlet:     "https://images.unsplash.com/photo-1522771739844-12a6a3537b32?w=600&h=600&fit=crop",
  realestate:   "https://images.unsplash.com/photo-1560518883-ce09059eefa8?w=600&h=600&fit=crop",
  mensuit:      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop",
  dress:        "https://images.unsplash.com/photo-1490481122-2788906a1c2d?w=600&h=600&fit=crop",
  kidsclothes:  "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop",
  womenheels:   "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop",
  kidsshoes:    "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&h=600&fit=crop",
  handbag:      "https://images.unsplash.com/photo-1548036161-65e073a23b3c?w=600&h=600&fit=crop",
  watch:        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
  jewelry:      "https://images.unsplash.com/photo-1509941943102-10c232535736?w=600&h=600&fit=crop",
  sunglasses:   "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop",
  kitchen:      "https://images.unsplash.com/photo-1556909114-f7bfbf4b4d09?w=600&h=600&fit=crop",
  bedding:      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=600&fit=crop",
  garden:       "https://images.unsplash.com/photo-1416879347-3b9e5cbad8f3?w=600&h=600&fit=crop",
  decor:        "https://images.unsplash.com/photo-1513694153478-aa81d73e5d68?w=600&h=600&fit=crop",
  fridge:       "https://images.unsplash.com/photo-1584568694-6e43b3e197c0?w=600&h=600&fit=crop",
  cleaning:     "https://images.unsplash.com/photo-1563453392212-326a3e5b4a36?w=600&h=600&fit=crop",
  art:          "https://images.unsplash.com/photo-1513364776144-e4d5e43ea0bf?w=600&h=600&fit=crop",
  storage:      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  skincare:     "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop",
  hair:         "https://images.unsplash.com/photo-1522337360429-a5fe65e4f1a5?w=600&h=600&fit=crop",
  perfume:      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=600&fit=crop",
  vitamins:     "https://images.unsplash.com/photo-1584308666838-a1b4532c70f7?w=600&h=600&fit=crop",
  medical:      "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=600&h=600&fit=crop",
  makeup:       "https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=600&h=600&fit=crop",
  firstaid:     "https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=600&h=600&fit=crop",
  scale:        "https://images.unsplash.com/photo-1535914184-2104978da4e2?w=600&h=600&fit=crop",
  dumbbell:     "https://images.unsplash.com/photo-1534438327-8a240a11e54a?w=600&h=600&fit=crop",
  camping:      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop",
  football:     "https://images.unsplash.com/photo-1518604964-dc33be4b7e2e?w=600&h=600&fit=crop",
  guitar:       "https://images.unsplash.com/photo-1510915361571-f2e2e95200a3?w=600&h=600&fit=crop",
  bicycle:      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=600&h=600&fit=crop",
  surfboard:    "https://images.unsplash.com/photo-1531722569936-825d4eebb6c1?w=600&h=600&fit=crop",
  finance:      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&h=600&fit=crop",
  officework:   "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=600&fit=crop",
  construction: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
  callcenter:   "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&h=600&fit=crop",
  engineer:     "https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=600&h=600&fit=crop",
  nurse:        "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=600&h=600&fit=crop",
  hotel:        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=600&fit=crop",
  hr:           "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop",
  coding:       "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=600&fit=crop",
  legal:        "https://images.unsplash.com/photo-1589578228447-e1a4e481c6c8?w=600&h=600&fit=crop",
  creative:     "https://images.unsplash.com/photo-1493612276216-ee3925520721?w=600&h=600&fit=crop",
  sales:        "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=600&fit=crop",
  teaching:     "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&h=600&fit=crop",
  driver:       "https://images.unsplash.com/photo-1449965408869-eef56a82b5a7?w=600&h=600&fit=crop",
  eventplan:    "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=600&fit=crop",
  tax:          "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&h=600&fit=crop",
  fitness:      "https://images.unsplash.com/photo-1534438327-8a240a11e54a?w=600&h=600&fit=crop",
  acrepair:     "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=600&fit=crop",
  movers:       "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=600&fit=crop",
  photo:        "https://images.unsplash.com/photo-1502920917128-1aa4a5be7fc5?w=600&h=600&fit=crop",
  phonerepair:  "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=600&fit=crop",
  freight:      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=600&fit=crop",
  travel:       "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=600&h=600&fit=crop",
  handyman:     "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
  dog:          "https://images.unsplash.com/photo-1518815701427-40a2b40a6b44?w=600&h=600&fit=crop",
  cat:          "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=600&fit=crop",
  parrot:       "https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=600&h=600&fit=crop",
  fishtank:     "https://images.unsplash.com/photo-1524704654-45c9e8e3d3b8?w=600&h=600&fit=crop",
  rabbit:       "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=600&fit=crop",
  petfood:      "https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=600&h=600&fit=crop",
  cow:          "https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=600&h=600&fit=crop",
  chicken:      "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&h=600&fit=crop",
  honey:        "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=600&fit=crop",
  waterpump:    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  tomatoes:     "https://images.unsplash.com/photo-1518977676405-d4ad8c873c78?w=600&h=600&fit=crop",
  farmland:     "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=600&fit=crop",
  fertilizer:   "https://images.unsplash.com/photo-1416879347-3b9e5cbad8f3?w=600&h=600&fit=crop",
  seeds:        "https://images.unsplash.com/photo-1416879347-3b9e5cbad8f3?w=600&h=600&fit=crop",
  babysuit:     "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop",
  babyshoes:    "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&h=600&fit=crop",
  babymonitor:  "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop",
  stroller:     "https://images.unsplash.com/photo-1586816879849-48b6a71f8555?w=600&h=600&fit=crop",
  lego:         "https://images.unsplash.com/photo-1558618402-d8562a7e2d76?w=600&h=600&fit=crop",
  babycare:     "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop",
  formula:      "https://images.unsplash.com/photo-1584308666838-a1b4532c70f7?w=600&h=600&fit=crop",
  carseat:      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop",
  biggen:       "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  welding:      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
  oven:         "https://images.unsplash.com/photo-1556909114-f7bfbf4b4d09?w=600&h=600&fit=crop",
  mixer:        "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
  pump:         "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  compressor:   "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=600&fit=crop",
  cctv:         "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&h=600&fit=crop",
  copier:       "https://images.unsplash.com/photo-1612198188060-c7c2a3b75bc8?w=600&h=600&fit=crop",
  palletruck:   "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=600&fit=crop",
};

export function getSeedProducts(findCat: FindCat, shopId: string): ProductSeed[] {
  return [
    // ── ELECTRONICS ───────────────────────────────────────────────────────────
    {
      title: "iPhone 15 Pro Max 256GB - Natural Titanium",
      description: "A17 Pro chip, 48MP camera system, USB-C, titanium frame. Battery up to 29 hours. Brand new, sealed.",
      price: "1199.00", stock: 15, condition: "NEW", location: "Lagos Island, Lagos",
      images: [P.iphone], categoryId: findCat("Mobile Phones"), shopId,
    },
    {
      title: "Apple iPad Air 5th Gen 256GB - Space Grey",
      description: "M1 chip, 10.9\" Liquid Retina display, 5G capable, USB-C. Perfect for work and creativity.",
      price: "749.00", stock: 10, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.tablet], categoryId: findCat("Tablets"), shopId,
    },
    {
      title: "Magsafe 15W Wireless Charger + Clear Case Bundle",
      description: "15W fast wireless charger with magnetic alignment. Includes military-grade clear phone case.",
      price: "29.00", stock: 50, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.electronics], categoryId: findCat("Mobile Phone Accessories"), shopId,
    },
    {
      title: "Panasonic KX-TGE433 Cordless Phone System",
      description: "Link2Cell Bluetooth, Talking Caller ID, enhanced noise reduction. Range up to 300m outdoors.",
      price: "45.00", stock: 20, condition: "NEW", location: "Abuja, FCT",
      images: [P.electronics], categoryId: findCat("Landline Phones"), shopId,
    },
    {
      title: "MacBook Pro 14\" M3 Pro - Space Black",
      description: "12-core CPU, 18-core GPU, 22-hour battery, Liquid Retina XDR display. Sealed box.",
      price: "1999.00", stock: 8, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.macbook], categoryId: findCat("Laptops & Computers"), shopId,
    },
    {
      title: "Logitech MX Master 3S Mouse + K380 Keyboard Combo",
      description: "Ultra-quiet clicks, 8K DPI, multi-device Bluetooth. Best-in-class productivity combo.",
      price: "89.00", stock: 30, condition: "NEW", location: "Lekki, Lagos",
      images: [P.keyboard], categoryId: findCat("Computer Accessories & Peripherals"), shopId,
    },
    {
      title: "TP-Link Archer AX73 WiFi 6 Router",
      description: "AX5400 speeds, 6 antennas, OFDMA & MU-MIMO, parental controls. Covers 2500 sq ft.",
      price: "89.00", stock: 18, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.router], categoryId: findCat("Networking Products"), shopId,
    },
    {
      title: "HP LaserJet Pro M404n Monochrome Printer",
      description: "40 ppm, 1200 dpi, auto duplex, USB & Ethernet. High monthly duty cycle for office use.",
      price: "155.00", stock: 12, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.printer], categoryId: findCat("Printers & Scanners"), shopId,
    },
    {
      title: "Dell UltraSharp 27\" 4K USB-C Monitor U2723D",
      description: "IPS panel, 100% sRGB, 60W USB-C charging, built-in KVM switch. Factory calibrated.",
      price: "449.00", stock: 7, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.monitor], categoryId: findCat("Computer Monitors"), shopId,
    },
    {
      title: "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
      description: "Industry-leading ANC, 30-hour battery, multipoint Bluetooth. New with full warranty.",
      price: "348.00", stock: 25, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.headphones], categoryId: findCat("Audio & Music Equipment"), shopId,
    },
    {
      title: "Samsung 65\" QLED 4K Smart TV Q80C",
      description: "Quantum Dot, 120Hz, Dolby Atmos, Gaming Hub, built-in Alexa. 2023 model.",
      price: "899.00", stock: 5, condition: "NEW", location: "Lekki, Lagos",
      images: [P.tv], categoryId: findCat("TV & DVD Equipment"), shopId,
    },
    {
      title: "Sony Alpha A7 IV Mirrorless Camera Body",
      description: "33MP full-frame BSI sensor, 4K60p video, 10fps burst, advanced AF. Body only.",
      price: "2499.00", stock: 4, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.camera], categoryId: findCat("Cameras, Photo & Video"), shopId,
    },
    {
      title: "PlayStation 5 Console (Disc Edition)",
      description: "4K gaming, 120fps support, ray tracing, 825GB SSD, DualSense controller included.",
      price: "499.00", stock: 6, condition: "NEW", location: "Computer Village, Lagos",
      images: [P.gaming], categoryId: findCat("Games & Consoles"), shopId,
    },
    {
      title: "Firman 3.2KVA Generator SPG3800E2 - Electric Start",
      description: "100% copper winding, electric start, dual fuel, 8 hours runtime. Ultra-quiet operation.",
      price: "195.00", stock: 20, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.generator], categoryId: findCat("Generators, UPS & Solar Energy"), shopId,
    },
    {
      title: "iPhone 13/14 Pro OLED Screen Replacement - Original",
      description: "OEM quality OLED display assembly with True Tone support. Comes with installation tools.",
      price: "89.00", stock: 40, condition: "NEW", location: "Computer Village, Lagos",
      images: [P.electronics], categoryId: findCat("Electronic Spare Parts & Accessories"), shopId,
    },

    // ── VEHICLES ─────────────────────────────────────────────────────────────
    {
      title: "Toyota Camry 2019 XLE V6 - Excellent Condition",
      description: "Foreign used, full leather interior, sunroof, backup camera, lane departure warning. Duty paid.",
      price: "18500.00", stock: 1, condition: "USED", location: "Lekki Phase 1, Lagos",
      images: [P.car], categoryId: findCat("Cars"), shopId,
    },
    {
      title: "Toyota HiAce 2018 LWB - 18 Seater Bus",
      description: "High roof, diesel, AC, TV unit. Perfect for transport business. Well maintained.",
      price: "28000.00", stock: 1, condition: "USED", location: "Mile 2, Lagos",
      images: [P.bus], categoryId: findCat("Buses & Microbuses"), shopId,
    },
    {
      title: "CAT 320 Hydraulic Excavator - 2017 Model",
      description: "2,500 machine hours, full working condition, new bucket. Available for purchase or hire.",
      price: "95000.00", stock: 1, condition: "USED", location: "Apapa, Lagos",
      images: [P.excavator], categoryId: findCat("Heavy Equipment"), shopId,
    },
    {
      title: "Honda CB500F 2021 - Naked Street Bike",
      description: "471cc parallel twin, ABS brakes, 6-speed, fuel injection. Low mileage, full service history.",
      price: "4200.00", stock: 1, condition: "USED", location: "Surulere, Lagos",
      images: [P.motorcycle], categoryId: findCat("Motorcycles & Bicycles"), shopId,
    },
    {
      title: "Man Diesel Truck 2016 - 30-Ton Flatbed",
      description: "Euro 5 engine, 6x4 drive, power steering, sleeper cab. Ready for heavy haulage.",
      price: "55000.00", stock: 1, condition: "USED", location: "Tin Can, Lagos",
      images: [P.truck], categoryId: findCat("Trucks & Trailers"), shopId,
    },
    {
      title: "Fiberglass Speed Boat 22ft - 150HP Outboard",
      description: "Yamaha 150HP engine, GPS, fish finder, live well, canopy. Ideal for Lagos waterways.",
      price: "12500.00", stock: 1, condition: "USED", location: "Apapa, Lagos",
      images: [P.boat], categoryId: findCat("Watercraft & Boats"), shopId,
    },
    {
      title: "18\" Sport Alloy Wheels Set of 4 - 5x114.3 PCD",
      description: "Fits Toyota, Honda, Lexus. Brand new with tyres. Sport design, silver finish.",
      price: "320.00", stock: 8, condition: "NEW", location: "Ladipo, Lagos",
      images: [P.carparts], categoryId: findCat("Vehicle Parts & Accessories"), shopId,
    },
    {
      title: "Toyota Corolla 2022 - Self Drive Car Rental (Per Day)",
      description: "Automatic, AC, GPS tracker, insurance included. Minimum 3-day booking.",
      price: "55.00", stock: 3, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.rental], categoryId: findCat("Car Rentals"), shopId,
    },

    // ── PROPERTY ─────────────────────────────────────────────────────────────
    {
      title: "3-Bedroom Apartment For Rent - Lekki Phase 1",
      description: "Fully serviced, 24/7 electricity, security, swimming pool, gym. ₦5.5M/year.",
      price: "3600.00", stock: 1, condition: "NEW", location: "Lekki Phase 1, Lagos",
      images: [P.apartment], categoryId: findCat("Houses & Apartments For Rent"), shopId,
    },
    {
      title: "4-Bedroom Detached House For Sale - Ikoyi",
      description: "3000 sqft BQ, 3 car garage, CCTV, backup generator. C of O available.",
      price: "280000.00", stock: 1, condition: "NEW", location: "Ikoyi, Lagos",
      images: [P.house], categoryId: findCat("Houses & Apartments For Sale"), shopId,
    },
    {
      title: "1000 sqm Land For Sale - Epe, Lagos",
      description: "Dry land, survey plan, deed of assignment. Family land, clean documents. Access road.",
      price: "18000.00", stock: 1, condition: "NEW", location: "Epe, Lagos",
      images: [P.land], categoryId: findCat("Land & Plots For Sale"), shopId,
    },
    {
      title: "5-Acre Agricultural Land For Lease - Ogun State",
      description: "Fenced, good road access, borehole available. 2-year lease with renewal option.",
      price: "2400.00", stock: 1, condition: "NEW", location: "Abeokuta, Ogun",
      images: [P.farmland], categoryId: findCat("Land & Plots For Rent"), shopId,
    },
    {
      title: "Open Plan Office Space 500sqm - Victoria Island",
      description: "Grade A office, central AC, 24/7 electricity, fibre internet, parking. ₦65M/year.",
      price: "43000.00", stock: 1, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.office], categoryId: findCat("Commercial Property For Rent"), shopId,
    },
    {
      title: "Showroom/Warehouse Complex For Sale - Isolo",
      description: "3000sqm, 4m ceiling height, 3-phase power, security post. Global C of O.",
      price: "650000.00", stock: 1, condition: "NEW", location: "Isolo, Lagos",
      images: [P.building], categoryId: findCat("Commercial Property For Sale"), shopId,
    },
    {
      title: "Luxury Studio Short Let - Eko Atlantic (Per Night)",
      description: "Fully furnished, ocean view, Netflix, WiFi, housekeeping. Minimum 3 nights.",
      price: "52.00", stock: 1, condition: "NEW", location: "Eko Atlantic, Lagos",
      images: [P.shortlet], categoryId: findCat("Short Let Property"), shopId,
    },
    {
      title: "Professional Property Survey & Valuation Service",
      description: "Licensed estate surveyor. Valuations, property searches, C of O processing, agency.",
      price: "120.00", stock: 20, condition: "NEW", location: "Ikeja GRA, Lagos",
      images: [P.realestate], categoryId: findCat("Real Estate Services"), shopId,
    },

    // ── FASHION ───────────────────────────────────────────────────────────────
    {
      title: "Slim-Fit 3-Piece Wool Suit - Navy Blue",
      description: "Italian wool blend, notch lapel, two-button closure. Sizes 38-48.",
      price: "185.00", stock: 20, condition: "NEW", location: "Lagos Island, Lagos",
      images: [P.mensuit], categoryId: findCat("Men's Clothing"), shopId,
    },
    {
      title: "Floral Midi Dress - Premium Chiffon",
      description: "V-neck, flowy silhouette, sizes S-XXL in 4 color options. Hand wash, air dry.",
      price: "55.00", stock: 35, condition: "NEW", location: "Balogun Market, Lagos",
      images: [P.dress], categoryId: findCat("Women's Clothing"), shopId,
    },
    {
      title: "Kids School Uniform Bundle - Ages 3-12",
      description: "2 shirts, 2 trousers/skirts, tie. 100% cotton, pre-shrunk. All school colors.",
      price: "22.00", stock: 60, condition: "NEW", location: "Tejuosho, Lagos",
      images: [P.kidsclothes], categoryId: findCat("Children's Clothing"), shopId,
    },
    {
      title: "Nike Air Max 270 - Men's Running Shoes",
      description: "Lightweight mesh upper, Max Air heel unit. Sizes 40-46. 100% Original Nike.",
      price: "89.00", stock: 30, condition: "NEW", location: "Computer Village, Lagos",
      images: [P.shoes], categoryId: findCat("Men's Shoes"), shopId,
    },
    {
      title: "Pointed Toe Stiletto Heels - Nude Beige",
      description: "4.5 inch heel, patent leather finish. Sizes 36-42. Perfect for formal events.",
      price: "48.00", stock: 25, condition: "NEW", location: "Tejuosho, Lagos",
      images: [P.womenheels], categoryId: findCat("Women's Shoes"), shopId,
    },
    {
      title: "Kids Light-Up Sneakers - Waterproof Sole",
      description: "LED lights, velcro strap, cushioned insole. Sizes EU 26-36. Machine washable.",
      price: "18.00", stock: 40, condition: "NEW", location: "Alaba, Lagos",
      images: [P.kidsshoes], categoryId: findCat("Children's Shoes"), shopId,
    },
    {
      title: "Genuine Leather Handbag - Italian Design",
      description: "Full grain leather, gold hardware, detachable strap. 3 internal compartments.",
      price: "95.00", stock: 15, condition: "NEW", location: "Lagos Island, Lagos",
      images: [P.handbag], categoryId: findCat("Bags"), shopId,
    },
    {
      title: "Casio G-Shock GA-2100 'CasiOak' - Carbon Black",
      description: "Carbon core guard structure, 200m water resistant, solar powered, world time.",
      price: "79.00", stock: 20, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.watch], categoryId: findCat("Watches"), shopId,
    },
    {
      title: "18K Gold Plated Cuban Link Chain Necklace 22\"",
      description: "5mm width, lobster clasp, tarnish resistant, hypoallergenic. Gift box included.",
      price: "35.00", stock: 30, condition: "NEW", location: "Balogun Market, Lagos",
      images: [P.jewelry], categoryId: findCat("Jewelry & Accessories"), shopId,
    },
    {
      title: "Polarized Aviator Sunglasses - UV400 Protection",
      description: "Metal frame, polarized lenses. Unisex design. Case and cleaning cloth included.",
      price: "19.00", stock: 50, condition: "NEW", location: "Alaba, Lagos",
      images: [P.sunglasses], categoryId: findCat("Other Fashion Items"), shopId,
    },

    // ── HOME, FURNITURE & APPLIANCES ─────────────────────────────────────────
    {
      title: "Modern L-Shaped Sectional Sofa - Smoke Grey",
      description: "Premium fabric upholstery, solid hardwood frame. Seats 5 comfortably.",
      price: "450.00", stock: 4, condition: "NEW", location: "Lekki, Lagos",
      images: [P.sofa], categoryId: findCat("Furniture & Decor"), shopId,
    },
    {
      title: "6-Piece Non-Stick Cookware Set - Granite Coated",
      description: "PFOA-free, induction compatible, dishwasher safe. Includes lids and wooden spoon set.",
      price: "65.00", stock: 20, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.kitchen], categoryId: findCat("Kitchen & Dining"), shopId,
    },
    {
      title: "Egyptian Cotton 600TC Duvet Set - King Size",
      description: "100% Egyptian cotton, hypoallergenic. Includes 2 pillowcases. Fits 38cm mattress.",
      price: "78.00", stock: 15, condition: "NEW", location: "Lekki, Lagos",
      images: [P.bedding], categoryId: findCat("Bedding & Linen"), shopId,
    },
    {
      title: "Rattan Garden Furniture Set - 4 Chairs + Table",
      description: "Weather-resistant PE rattan, powder-coated steel frame, cushions included.",
      price: "220.00", stock: 6, condition: "NEW", location: "Lekki, Lagos",
      images: [P.garden], categoryId: findCat("Garden & Outdoor"), shopId,
    },
    {
      title: "Abstract Canvas Wall Art Set - 3 Pieces",
      description: "Contemporary art on premium stretched canvas. Each piece 40x60cm. Ready to hang.",
      price: "45.00", stock: 25, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.decor], categoryId: findCat("Home Accessories & Decor"), shopId,
    },
    {
      title: "Samsung 350L Side-by-Side Refrigerator - Silver",
      description: "Digital inverter, 5-year compressor warranty, water dispenser, auto deodorizer.",
      price: "490.00", stock: 5, condition: "NEW", location: "Apapa, Lagos",
      images: [P.fridge], categoryId: findCat("Household Appliances"), shopId,
    },
    {
      title: "Karcher K2 Compact Pressure Washer",
      description: "1400W, 1400 psi, 11L/min flow, car wash kit included. Ideal for patio and cars.",
      price: "89.00", stock: 12, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.cleaning], categoryId: findCat("Household Cleaning Supplies"), shopId,
    },
    {
      title: "Professional Artist Acrylic Paint Set - 48 Colors",
      description: "Heavy body acrylics, lightfast, 75ml tubes. Includes 3 brushes and palette knives.",
      price: "55.00", stock: 20, condition: "NEW", location: "Surulere, Lagos",
      images: [P.art], categoryId: findCat("Arts & Crafts"), shopId,
    },
    {
      title: "KALLAX 4-Cube Shelf Unit - White",
      description: "Sturdy MDF, can be used standing or lying. Compatible with KALLAX inserts.",
      price: "65.00", stock: 10, condition: "NEW", location: "Lekki, Lagos",
      images: [P.decor], categoryId: findCat("Other Home Items"), shopId,
    },

    // ── HEALTH & BEAUTY ───────────────────────────────────────────────────────
    {
      title: "Oral-B iO Series 7 Electric Toothbrush",
      description: "Magnetic brush drive, 5 smart modes, pressure sensor, 2 replacement heads, travel case.",
      price: "89.00", stock: 18, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.skincare], categoryId: findCat("Personal Care & Hygiene"), shopId,
    },
    {
      title: "100% Brazilian Virgin Human Hair Straight 24\"",
      description: "Unprocessed human hair, can be dyed and heat styled. 3 bundles with lace closure.",
      price: "145.00", stock: 15, condition: "NEW", location: "Balogun Market, Lagos",
      images: [P.hair], categoryId: findCat("Hair & Extensions"), shopId,
    },
    {
      title: "Dior Sauvage Eau de Parfum 100ml",
      description: "Fresh spicy fragrance, long lasting 8+ hours. Original with batch code. Boxed and sealed.",
      price: "89.00", stock: 20, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.perfume], categoryId: findCat("Fragrance & Deodorant"), shopId,
    },
    {
      title: "Optimum Nutrition Gold Standard 100% Whey - 5lb",
      description: "24g protein per serving, 5.5g BCAAs, 4g glutamine. Chocolate flavor. Lab tested.",
      price: "65.00", stock: 25, condition: "NEW", location: "Surulere, Lagos",
      images: [P.vitamins], categoryId: findCat("Vitamins & Supplements"), shopId,
    },
    {
      title: "Omron M3 Upper Arm Blood Pressure Monitor",
      description: "Clinically validated, detects irregular heartbeat, 60-reading memory.",
      price: "48.00", stock: 22, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.medical], categoryId: findCat("Health Products"), shopId,
    },
    {
      title: "15-Piece Professional Makeup Brush Set with Case",
      description: "Synthetic bristles, cruelty free. Includes foundation, powder, contour, blending brushes.",
      price: "32.00", stock: 30, condition: "NEW", location: "Balogun Market, Lagos",
      images: [P.makeup], categoryId: findCat("Beauty Tools & Accessories"), shopId,
    },
    {
      title: "CeraVe AM Facial Moisturising Lotion SPF 50",
      description: "Broad spectrum SPF 50, hyaluronic acid, niacinamide. Lightweight, non-comedogenic. 52ml.",
      price: "22.00", stock: 40, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.skincare], categoryId: findCat("Skin Care"), shopId,
    },
    {
      title: "FirstAid Kit - 200-Piece Professional Kit",
      description: "OSHA/ANSI compliant, waterproof hard case, bandages, antiseptics, CPR mask, gloves.",
      price: "38.00", stock: 30, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.firstaid], categoryId: findCat("Medical Supplies"), shopId,
    },
    {
      title: "RENPHO Smart Body Composition Scale - Bluetooth",
      description: "13 body metrics via app, 180kg capacity, measures BMI, muscle, fat, bone mass.",
      price: "28.00", stock: 20, condition: "NEW", location: "Lekki, Lagos",
      images: [P.scale], categoryId: findCat("Weight Loss Products"), shopId,
    },

    // ── SPORTS, ARTS & OUTDOORS ────────────────────────────────────────────────
    {
      title: "Adjustable Dumbbell Set 5-25kg Per Dumbbell",
      description: "Quick-adjust selector, replaces 5 pairs of dumbbells. Non-slip handle, secure tray.",
      price: "185.00", stock: 8, condition: "NEW", location: "Surulere, Lagos",
      images: [P.dumbbell], categoryId: findCat("Exercise & Fitness"), shopId,
    },
    {
      title: "4-Person Camping Tent - Waterproof Instant Setup",
      description: "Sets up in 60 seconds, 3000mm waterproof rating, ventilation windows, gear loft.",
      price: "75.00", stock: 12, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.camping], categoryId: findCat("Outdoor Recreation & Camping"), shopId,
    },
    {
      title: "Adidas Champions League Match Ball - Size 5",
      description: "FIFA quality pro, thermally bonded seamless, high-bounce butyl bladder.",
      price: "35.00", stock: 25, condition: "NEW", location: "Surulere, Lagos",
      images: [P.football], categoryId: findCat("Sporting Goods"), shopId,
    },
    {
      title: "Yamaha F310 Acoustic Guitar - Full Size",
      description: "Spruce top, meranti back & sides, diecast tuners. Includes gig bag, picks, strap, tuner.",
      price: "95.00", stock: 10, condition: "NEW", location: "Surulere, Lagos",
      images: [P.guitar], categoryId: findCat("Musical Instruments"), shopId,
    },
    {
      title: "Copic Sketch Markers Set - 24 Essential Colors",
      description: "Alcohol-based, refillable, replaceable nibs. Dual tip (broad & brush). Archival quality.",
      price: "89.00", stock: 10, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.art], categoryId: findCat("Art & Craft Supplies"), shopId,
    },
    {
      title: "Trek Marlin 5 Mountain Bike - 29\" (2023)",
      description: "Hydraulic disc brakes, 21-speed Shimano, aluminum frame, suspension fork.",
      price: "549.00", stock: 5, condition: "NEW", location: "Lekki, Lagos",
      images: [P.bicycle], categoryId: findCat("Bicycles"), shopId,
    },
    {
      title: "Inflatable Stand-Up Paddleboard 10ft",
      description: "15cm thick, 150kg capacity. Includes pump, paddle, leash, carry bag.",
      price: "320.00", stock: 4, condition: "NEW", location: "Elegushi Beach, Lagos",
      images: [P.surfboard], categoryId: findCat("Water Sports"), shopId,
    },

    // ── JOBS ──────────────────────────────────────────────────────────────────
    {
      title: "Senior Accountant - ICAN Certified (₦250k–₦350k/month)",
      description: "5 years experience, SAGE & QuickBooks, tax compliance, financial reporting.",
      price: "250.00", stock: 1, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.finance], categoryId: findCat("Accounting & Finance"), shopId,
    },
    {
      title: "Executive Assistant / Office Manager - Available Now",
      description: "8 years executive support, MS Office, scheduling, travel management.",
      price: "150.00", stock: 1, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.officework], categoryId: findCat("Administrative & Office"), shopId,
    },
    {
      title: "Master Mason & Tiling Specialist - 15 Years Experience",
      description: "Expert in Italian porcelain, granite, terrazzo. References available.",
      price: "80.00", stock: 1, condition: "NEW", location: "Surulere, Lagos",
      images: [P.construction], categoryId: findCat("Construction & Artisans"), shopId,
    },
    {
      title: "Customer Service Rep / Call Centre Agent",
      description: "3 years call centre experience, CRM tools, excellent communication. Available immediately.",
      price: "90.00", stock: 1, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.callcenter], categoryId: findCat("Customer Service"), shopId,
    },
    {
      title: "Electrical Engineer (COREN Registered) - Project Work",
      description: "Power systems, PLC programming, AutoCAD, 10+ years. Contract & permanent.",
      price: "400.00", stock: 1, condition: "NEW", location: "Port Harcourt, Rivers",
      images: [P.engineer], categoryId: findCat("Engineering & Technical"), shopId,
    },
    {
      title: "Registered Nurse (RN) - ICU Trained, Seeking Placement",
      description: "BSc Nursing, 7 years ICU/HDU experience, BLS & ACLS certified.",
      price: "300.00", stock: 1, condition: "NEW", location: "Abuja, FCT",
      images: [P.nurse], categoryId: findCat("Healthcare"), shopId,
    },
    {
      title: "Hotel Manager - 4/5 Star Experience",
      description: "12 years hospitality, revenue management, team leadership, F&B operations.",
      price: "500.00", stock: 1, condition: "NEW", location: "Lagos",
      images: [P.hotel], categoryId: findCat("Hospitality & Hotel"), shopId,
    },
    {
      title: "HR Manager / CIPM Member - Open to Opportunities",
      description: "CIPM certified, payroll, recruitment, ER, policy development, 8 years experience.",
      price: "250.00", stock: 1, condition: "NEW", location: "Lagos",
      images: [P.hr], categoryId: findCat("Human Resources"), shopId,
    },
    {
      title: "Full-Stack Developer (React/Node.js) - Freelance & Full-Time",
      description: "6 years experience, TypeScript, AWS, PostgreSQL. Remote or onsite Lagos.",
      price: "500.00", stock: 1, condition: "NEW", location: "Lagos",
      images: [P.coding], categoryId: findCat("IT & Telecoms"), shopId,
    },
    {
      title: "Barrister & Solicitor - Corporate/Commercial Law",
      description: "10 years call, company secretarial, contracts, litigation support. Chambers in VI.",
      price: "200.00", stock: 1, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.legal], categoryId: findCat("Legal"), shopId,
    },
    {
      title: "Creative Director / Brand Strategist - Available for Hire",
      description: "10 years brand & creative, TV commercials, digital campaigns, FMCG & fintech.",
      price: "450.00", stock: 1, condition: "NEW", location: "Lagos",
      images: [P.creative], categoryId: findCat("Media & Advertising"), shopId,
    },
    {
      title: "Sales Manager (FMCG) - Seeking New Challenge",
      description: "12 years sales management, team of 30, ₦500M+ targets. MBA, CIM qualified.",
      price: "350.00", stock: 1, condition: "NEW", location: "Ibadan, Oyo",
      images: [P.sales], categoryId: findCat("Sales & Marketing"), shopId,
    },
    {
      title: "Qualified Mathematics Teacher - Secondary School Level",
      description: "B.Ed Mathematics, WAEC/JAMB specialist, 9 years. Lagos & remote tutoring.",
      price: "100.00", stock: 1, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.teaching], categoryId: findCat("Teaching & Education"), shopId,
    },
    {
      title: "Professional Driver / Personal Driver - 10 Years",
      description: "Defensive driving certified, clean record, familiar with Lagos/Abuja roads.",
      price: "80.00", stock: 1, condition: "NEW", location: "Lagos",
      images: [P.driver], categoryId: findCat("Other Jobs"), shopId,
    },

    // ── SERVICES ─────────────────────────────────────────────────────────────
    {
      title: "General Building Construction & Renovation Services",
      description: "New builds, extensions, renovations. Bill of quantities, project management.",
      price: "500.00", stock: 10, condition: "NEW", location: "Surulere, Lagos",
      images: [P.construction], categoryId: findCat("Building & Construction"), shopId,
    },
    {
      title: "Deep Clean & Fumigation Service - Homes & Offices",
      description: "End-of-tenancy, post-construction, pest control. Eco-friendly products. Same-day.",
      price: "45.00", stock: 20, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.cleaning], categoryId: findCat("Cleaning & Fumigation"), shopId,
    },
    {
      title: "Laptop & Desktop Repair - All Brands",
      description: "Screen replacements, virus removal, OS installation, data recovery. 30-day warranty.",
      price: "25.00", stock: 30, condition: "NEW", location: "Computer Village, Lagos",
      images: [P.coding], categoryId: findCat("Computer & Technology"), shopId,
    },
    {
      title: "PMP & Prince2 Certification Training - 5-Day Bootcamp",
      description: "Accredited training, exam voucher included, study materials, mock tests. Pass guarantee.",
      price: "250.00", stock: 15, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.teaching], categoryId: findCat("Education & Training"), shopId,
    },
    {
      title: "Full Event Planning Service - Weddings & Corporate",
      description: "Venue sourcing, catering coordination, décor, MC, entertainment. Up to 500 guests.",
      price: "800.00", stock: 5, condition: "NEW", location: "Lekki, Lagos",
      images: [P.eventplan], categoryId: findCat("Event Planning & Entertainment"), shopId,
    },
    {
      title: "Personal & Business Tax Advisory Service",
      description: "FIRS filing, tax planning, audit support, PAYE management. Registered tax consultant.",
      price: "150.00", stock: 10, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.tax], categoryId: findCat("Financial Services"), shopId,
    },
    {
      title: "Personal Training & Nutrition Coaching - 12-Week Program",
      description: "Certified PT, customized workout plan, diet plan, weekly check-ins. Online & in-person.",
      price: "180.00", stock: 10, condition: "NEW", location: "Lekki, Lagos",
      images: [P.fitness], categoryId: findCat("Health & Wellness"), shopId,
    },
    {
      title: "AC Installation & Servicing - All Brands & Tonnages",
      description: "Split unit installation, gas recharge, deep cleaning, fault diagnosis. Emergency call-outs.",
      price: "35.00", stock: 20, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.acrepair], categoryId: findCat("Home & Office Maintenance"), shopId,
    },
    {
      title: "Professional Movers & Packers - Lagos & Interstate",
      description: "Packing, loading, transport, unpacking. Insurance on all goods. All truck sizes.",
      price: "95.00", stock: 10, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.movers], categoryId: findCat("Moving & Relocation"), shopId,
    },
    {
      title: "Wedding Photography & Videography - Full Day Package",
      description: "2 photographers + videographer, drone footage, same-day edit reel, 500+ edited photos.",
      price: "800.00", stock: 5, condition: "NEW", location: "Lekki, Lagos",
      images: [P.photo], categoryId: findCat("Photography & Videography"), shopId,
    },
    {
      title: "iPhone & Android Screen Repair - Same Day",
      description: "Original OLED/LCD screens, 90-day warranty. All models including iPhone 15 Pro.",
      price: "35.00", stock: 50, condition: "NEW", location: "Computer Village, Lagos",
      images: [P.phonerepair], categoryId: findCat("Repair Services"), shopId,
    },
    {
      title: "Lagos–Abuja Freight & Courier (Per kg)",
      description: "Door-to-door pickup & delivery, GPS tracking, same-day and next-day options.",
      price: "2.50", stock: 100, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.freight], categoryId: findCat("Transport & Freight"), shopId,
    },
    {
      title: "UK/Canada/US Visa Application Assistance",
      description: "Document checklist, DS-160 support, appointment booking, travel insurance. 80% success.",
      price: "120.00", stock: 20, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.travel], categoryId: findCat("Travel & Visa"), shopId,
    },
    {
      title: "Handyman Service - Plumbing, Electrical, Carpentry",
      description: "Multi-skilled handyman for home repairs. Toilet repairs, light fittings, assembly.",
      price: "20.00", stock: 30, condition: "NEW", location: "Surulere, Lagos",
      images: [P.handyman], categoryId: findCat("Other Services"), shopId,
    },

    // ── ANIMALS & PETS ─────────────────────────────────────────────────────────
    {
      title: "German Shepherd Puppy - 8 Weeks Old, Pure Breed",
      description: "Parents health tested, microchipped, first vaccination done, vet certificate.",
      price: "350.00", stock: 3, condition: "NEW", location: "Gbagada, Lagos",
      images: [P.dog], categoryId: findCat("Dogs"), shopId,
    },
    {
      title: "Persian Kitten - 10 Weeks, Litter Trained",
      description: "Blue point coloring, vet checked, wormed, first vaccine, very friendly.",
      price: "180.00", stock: 2, condition: "NEW", location: "Lekki, Lagos",
      images: [P.cat], categoryId: findCat("Cats"), shopId,
    },
    {
      title: "African Grey Parrot - 6 Months Old, Hand Tame",
      description: "Hand tame from birth, vet card, cage included. 40+ word vocabulary.",
      price: "420.00", stock: 1, condition: "NEW", location: "Gbagada, Lagos",
      images: [P.parrot], categoryId: findCat("Birds"), shopId,
    },
    {
      title: "60-Litre Tropical Aquarium Complete Setup",
      description: "Tank, filter, LED light, heater, substrate, plants, 20 assorted tropical fish.",
      price: "120.00", stock: 4, condition: "NEW", location: "Surulere, Lagos",
      images: [P.fishtank], categoryId: findCat("Fish & Aquariums"), shopId,
    },
    {
      title: "Holland Lop Rabbit - 8 Weeks, White & Grey",
      description: "Lop ears, gentle nature, litter trained. Includes cage, hay feeder, water bottle.",
      price: "65.00", stock: 2, condition: "NEW", location: "Gbagada, Lagos",
      images: [P.rabbit], categoryId: findCat("Other Pets"), shopId,
    },
    {
      title: "Royal Canin German Shepherd Adult Dog Food - 15kg",
      description: "Breed-specific nutrition, joint support, omega fatty acids for skin and coat health.",
      price: "55.00", stock: 25, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.petfood], categoryId: findCat("Pet Food & Accessories"), shopId,
    },
    {
      title: "Friesian Cross Dairy Cow - High Milk Yield",
      description: "3 years old, currently in milk, 15 liters/day. Healthy, vaccinated.",
      price: "850.00", stock: 2, condition: "NEW", location: "Ibadan, Oyo",
      images: [P.cow], categoryId: findCat("Farm Animals"), shopId,
    },
    {
      title: "Point-of-Lay ISA Brown Laying Hens - Batch of 100",
      description: "18 weeks old, fully vaccinated (Newcastle, Marek's, Gumboro). Ready to lay.",
      price: "280.00", stock: 5, condition: "NEW", location: "Abeokuta, Ogun",
      images: [P.chicken], categoryId: findCat("Livestock"), shopId,
    },

    // ── FOOD & AGRICULTURE ───────────────────────────────────────────────────
    {
      title: "Organic Honey - 100% Raw Unfiltered - 1kg Jar",
      description: "Harvested from Oyo State farms, no additives, rich in antioxidants. Lab certified.",
      price: "12.00", stock: 60, condition: "NEW", location: "Ibadan, Oyo",
      images: [P.honey], categoryId: findCat("Food & Drinks"), shopId,
    },
    {
      title: "Honda GX160 Petrol Water Pump 2\" - Farm Irrigation",
      description: "72m head, 36,000L/hour flow rate, 5.5HP Honda engine. Ideal for irrigation.",
      price: "185.00", stock: 10, condition: "NEW", location: "Bodija, Ibadan",
      images: [P.waterpump], categoryId: findCat("Farming Equipment & Tools"), shopId,
    },
    {
      title: "Fresh Tomatoes - Farm Gate Direct (50kg Bag)",
      description: "Plum tomatoes, freshly harvested, Grade A. Wholesale direct from Kano farms.",
      price: "18.00", stock: 50, condition: "NEW", location: "Mile 12, Lagos",
      images: [P.tomatoes], categoryId: findCat("Farm Produce"), shopId,
    },
    {
      title: "10-Acre Farmland For Sale - Ogun State",
      description: "Fertile loamy soil, perimeter fencing, borehole, access road. C of O available.",
      price: "22000.00", stock: 1, condition: "NEW", location: "Ogun Waterside, Ogun",
      images: [P.farmland], categoryId: findCat("Agricultural Land & Farms"), shopId,
    },
    {
      title: "NPK 15-15-15 Fertilizer - 50kg Bag",
      description: "Balanced compound fertilizer, suitable for all crops. Nafdac approved.",
      price: "32.00", stock: 100, condition: "NEW", location: "Bodija, Ibadan",
      images: [P.fertilizer], categoryId: findCat("Fertilizers & Pesticides"), shopId,
    },
    {
      title: "Hybrid Maize Seed UNAHYA 2000 - 10kg Bag",
      description: "High yield, drought tolerant, 90-day maturity, 8-10 tonnes/hectare potential.",
      price: "28.00", stock: 40, condition: "NEW", location: "Abuja, FCT",
      images: [P.seeds], categoryId: findCat("Seeds & Plants"), shopId,
    },

    // ── KIDS ITEMS ────────────────────────────────────────────────────────────
    {
      title: "Carter's Baby Boy 5-Piece Onesie Set - Newborn–12M",
      description: "100% cotton, snap closures, preshrunk. Mix of long & short sleeve. Machine washable.",
      price: "28.00", stock: 30, condition: "NEW", location: "Lekki, Lagos",
      images: [P.babysuit], categoryId: findCat("Baby & Kids Clothes"), shopId,
    },
    {
      title: "Nike Kids Air Max SC Toddler - Sizes EU 20-27",
      description: "Velcro strap, foam midsole, durable rubber outsole. Original Nike.",
      price: "45.00", stock: 20, condition: "NEW", location: "Alaba, Lagos",
      images: [P.babyshoes], categoryId: findCat("Baby & Kids Shoes"), shopId,
    },
    {
      title: "Baby Monitor with Camera - 5\" HD Night Vision",
      description: "5\" split screen, 2-way audio, temperature sensor, lullabies, 300m range.",
      price: "65.00", stock: 12, condition: "NEW", location: "Lekki, Lagos",
      images: [P.babymonitor], categoryId: findCat("Baby & Kids Accessories"), shopId,
    },
    {
      title: "Chicco Bravo Trio Travel System Stroller - Jet Black",
      description: "With infant car seat, one-hand fold, UPF50+ canopy, all-wheel suspension.",
      price: "280.00", stock: 4, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.stroller], categoryId: findCat("Strollers & Prams"), shopId,
    },
    {
      title: "LEGO Technic Lamborghini Huracán Tecnica 42161",
      description: "806 pieces, authentic V10 engine movement, detailed interior, display quality.",
      price: "49.00", stock: 8, condition: "NEW", location: "Lekki, Lagos",
      images: [P.lego], categoryId: findCat("Toys"), shopId,
    },
    {
      title: "Dove Baby Head-to-Toe Wash & Lotion Set",
      description: "Tear-free, hypoallergenic, dermatologist tested. 400ml wash + 400ml lotion.",
      price: "18.00", stock: 40, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.babycare], categoryId: findCat("Baby Care"), shopId,
    },
    {
      title: "Aptamil Profutura Stage 1 Baby Formula - 800g",
      description: "Birth to 6 months, prebiotics, DHA, ARA. Closest formula to breast milk.",
      price: "35.00", stock: 30, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.formula], categoryId: findCat("Baby Food & Feeding"), shopId,
    },
    {
      title: "Graco Extend2Fit 3-in-1 Convertible Car Seat",
      description: "Rear-facing to 50 lbs, forward-facing to 65 lbs. 6 recline positions, side impact tested.",
      price: "159.00", stock: 6, condition: "NEW", location: "Lekki, Lagos",
      images: [P.carseat], categoryId: findCat("Car Seats"), shopId,
    },

    // ── COMMERCIAL EQUIPMENT & TOOLS ─────────────────────────────────────────
    {
      title: "Perkins 100KVA Diesel Generator - Soundproof",
      description: "1500 RPM, 50Hz, deep sea controller, auto-start, AVR. 1-year warranty.",
      price: "12500.00", stock: 2, condition: "NEW", location: "Apapa, Lagos",
      images: [P.biggen], categoryId: findCat("Generators & Power Equipment"), shopId,
    },
    {
      title: "Lincoln Electric MIG Welder 180 Amp - 3-in-1",
      description: "MIG, TIG & stick, gas/gasless, LCD display, 60% duty cycle. Includes accessories.",
      price: "390.00", stock: 5, condition: "NEW", location: "Mushin, Lagos",
      images: [P.welding], categoryId: findCat("Fabrication & Metalworking"), shopId,
    },
    {
      title: "Commercial Convection Oven 4-Tray - Electric 3KW",
      description: "304 stainless steel, fan-forced, independent top/bottom controls, timer. Bakery grade.",
      price: "480.00", stock: 3, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.oven], categoryId: findCat("Food Production & Catering Equipment"), shopId,
    },
    {
      title: "Concrete Mixer 500L - Diesel Powered",
      description: "500L drum, 15HP diesel engine, rubber tyres for site mobility. High output.",
      price: "2200.00", stock: 2, condition: "NEW", location: "Apapa, Lagos",
      images: [P.mixer], categoryId: findCat("Heavy Industrial Equipment"), shopId,
    },
    {
      title: "Grundfos CM3-6 Centrifugal Water Pump 0.5HP",
      description: "Stainless steel impeller, 5.5m³/hr flow, 47m head, self-draining. For clean water.",
      price: "185.00", stock: 8, condition: "NEW", location: "Apapa, Lagos",
      images: [P.pump], categoryId: findCat("Industrial Pumps"), shopId,
    },
    {
      title: "Chicago Pneumatic 50L Air Compressor - 3HP 10 Bar",
      description: "Oil-lubricated, 50L tank, 180L/min, thermal overload protection. Includes hose kit.",
      price: "320.00", stock: 5, condition: "NEW", location: "Trade Fair, Lagos",
      images: [P.compressor], categoryId: findCat("Air Compressors"), shopId,
    },
    {
      title: "4-Channel CCTV Kit - 4x4MP Cameras + 1TB DVR",
      description: "Full HD day/night, 30m IR, weatherproof, phone alerts. Easy DIY install.",
      price: "195.00", stock: 10, condition: "NEW", location: "Ikeja, Lagos",
      images: [P.cctv], categoryId: findCat("Safety & Security Equipment"), shopId,
    },
    {
      title: "Canon iR2625i A3 Photocopier - Print/Copy/Scan",
      description: "25ppm, duplex, 2x500 sheet trays, network ready, 60-page ADF. Starter toner.",
      price: "850.00", stock: 3, condition: "NEW", location: "Victoria Island, Lagos",
      images: [P.copier], categoryId: findCat("Office Equipment & Supplies"), shopId,
    },
    {
      title: "Electric Pallet Truck 1000kg - Lithium Battery",
      description: "1000kg capacity, 8-hour runtime lithium battery, ergonomic handle, quick charge.",
      price: "1200.00", stock: 2, condition: "NEW", location: "Apapa, Lagos",
      images: [P.palletruck], categoryId: findCat("Other Commercial Equipment"), shopId,
    },
  ];
}
